version: '2.3'

services:
  drama:
    build:
      context: .
    volumes:
      - "./:/opt/Drama/service"
    environment:
      - PYTHONPATH="opt/Drama/service"
      - REDIS_URL=redis://redis
      - DATABASE_URL=postgresql://postgres@postgres:5432/postgres
      - DATABASE_CONNECTION_POOL_URL=postgresql://postgres@postgres:5432/postgres
      - MASTER_KEY=${MASTER_KEY:-KTVciAUQFpFh2WdJ/oiHJlxl6FvzRZp8kYzAAv3l2OA=}
      - domain=localhost
      - SITE_NAME=Drama
      - CLOUDFLARE_ZONE=vcxvdfgfc6r554etrgd
      - CLOUDFLARE_KEY=vcxvdfgfc6r554etrgd
      - TENOR_KEY=vcxvdfgfc6r554etrgd
      - MAILGUN_KEY=vcxvdfgfc6r554etrgd
      - MAILGUN_DOMAIN=rdrama.net
      - admin_email=drama@rdrama.net
      - FORCE_HTTPS=0
      - DISCORD_SERVER_ID=vcxvdfgfc6r554etrgd
      - DISCORD_CLIENT_ID=vcxvdfgfc6r554etrgd
      - DISCORD_CLIENT_SECRET=vcxvdfgfc6r554etrgd
      - DISCORD_BOT_TOKEN=vcxvdfgfc6r554etrgd
      - imgurkey=vcxvdfgfc6r554etrgd
      - FACEBOOK_TOKEN=vcxvdfgfc6r554etrgd
        #- HCAPTCHA_SITEKEY=vcxvdfgfc6r554etrgd
      - HCAPTCHA_SECRET=vcxvdfgfc6r554etrgd
      - youtubekey=vcxvdfgfc6r554etrgd
      - PUSHER_KEY=vcxvdfgfc6r554etrgd
    links:
      - "redis"
      - "postgres"
    ports:
      - "80:80"
    depends_on:
      - redis
      - postgres

  redis:
    image: redis
    volumes:
      - ./redis.conf:/opt/Drama/redis.conf
    ports:
      - "6379:6379"

  postgres:
    image: postgres:12.3
    volumes:
      - "./schema.sql:/docker-entrypoint-initdb.d/00-schema.sql"
      - "./seed-db.sql:/docker-entrypoint-initdb.d/01-schema.sql"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
